image: node:12

stages:
  - check
  - build
  - test

check-install:
  script:
    - yarn install --immutable --immutable-cache
  stage: check
check-constraints:
  script:
    - yarn constraints
  stage: check
check-format:
  script:
    - yarn run lint:format
  stage: check

build:
  script:
    - yarn run build
  stage: build

test:
  script:
    - yarn run test --coverage
  artifacts:
    paths:
      - coverage
  stage: test
